### ISSUE TITLE
Tag sizes

### ISSUE THREAD

**Issue by pbeeson** [AprilRobotics/apriltag#110]
As a long time user of the Apriltag library, I started using v3 recently, and wasted many hours trying to figure out why pose estimation of tagStandard41h12 was so bad.  In previous versions of the library, tags were measured to the outer border.  But with v3 it looks like this isn't necessarily the case.   I finally figured out by the following what the problem was by piecing together these two bits of information:

> AprilTag 3 supports a wide variety of possible tag layouts in addition to the classic layout supported in AprilTag 2. The tag's data bits can now go outside of the tag border, and it is also possible to define layouts with "holes" inside of the tag border where there are no data bits. 

> Each tag design has a black border and a white border, but some designs have the white border on the inside and some have the black border on the inside. The tagsize is thus measured from where the two borders meet, see the figure below for an example.

1) There is no example provided, which I think would have been the minimal thing that would have clued me in that my tag size (measured as the size I told the .png to print at, which is 9/5 (1.8x) larger than the expected tagsize) was the culprit.  I eventually figured tiis out once I started visualizing the corners of the detected tags, and realized the corners were inside the actual area of the printed tag.  So perhaps only documentation updates are needed.

2) But, I'm unsure how this affects other tag families, so I'm proposing that it might be useful to actually let users define the tag size as the actual size of EVERY pixel printed from the .png, then internally do a scaling factor (e.g. divide by 1.8 for standard41h12).  This way the user can send a .png to the printer to print at N mm, and easily enter N as the tag size without having to measure to do the scaling down to an internal border themselves, offline.

**Comment by mkrogius** [comment]
1. I've added a note + illustration to the end of the User Guide to address this which should define what tag size should be for any sort of tag family.

2.  At this point we cannot redefine the meaning of "Tag Size". In addition its probably always a good idea to manually measure the size just in case the printer applied some scaling.
