### ISSUE TITLE
pose estimation

### ISSUE THREAD

**Issue by shaoxuan92** [AprilRobotics/apriltag#114]
When I use estimate_tag_pose() function to estimate camera pose, I found that the pose flickers sometimes( shown in the image)(The pose seems symmetry to some extent). I bypass this by adding a constraint since my camera is always lower than the tag. (I compute the camera coordinate in the apritag coordinate, and delete poses whose pose.t.y<0). 
`cv::Mat mTestAccuracy = mTagToCamera.inv();`
`if( mTestAccuracy.at<float>(1,3)>0) {}`
And this really filters most of false poses. However, there are still some false poses(Intuitvely, the camera moves in (x>0,y>0,z<0 in the apriltag coordinate, the pose with mTestAccuracy.at<float>(0,3)<0 occurs sometimes).

 I wonder is it the reason that there are some bugs in computing pose from homography?

![Screenshot from 2020-11-25 14-15-47](https://user-images.githubusercontent.com/15856240/100190239-c8438e80-2f28-11eb-9042-24c80e7618f1.png)

**Comment by mkrogius** [comment]
There is no way I can answer that without seeing the image of the tag.
