### ISSUE TITLE
Build apriltag lib and python wrapper without building demo/examples?

### ISSUE THREAD

**Issue by ebradbury** [AprilRobotics/apriltag#115]
Hi,

In the install docs it says "you can speed up the installation by deleting the files tagCircle49h12.c, tagCircle49h12.h, tagCustom48h12.c, tagCustom48h12.h, tagStandard52h13.c, and tagStandard52h13.h before installing". However if I delete those files and proceed with `cmake .` and `make install` it fails with "fatal error: tagCircle49h12.h: No such file or directory" while trying to compile `apriltag_demo`.

Is there a way to skip the demo build but still have the lib and python wrapper install?

Thanks

**Comment by mkrogius** [comment]
Deleting these files should no longer change the build speed very much.
