### ISSUE TITLE
Compiling under Windows 10 - Mingw? other methods?

### ISSUE THREAD

**Issue by sleeplessTLV** [AprilRobotics/apriltag#124]
Hi All,
for various reasons (H/W, drivers) I need to use the April Tag  3 library on machines running Windows 10. I cannot use a virtual linux machine on that system - it needs to run under Windows, but I can use a GCC version or whatever. The key issue is the pthread Linux depedency.
Can you suggest a simple (even quick & dirty) way to compile/get an exe?
thanks

**Comment by mkrogius** [comment]
The following threads discuss how other people were able to get it to run on windows:
https://github.com/AprilRobotics/apriltag/pull/27
https://github.com/AprilRobotics/apriltag/issues/37
