### ISSUE TITLE
Python3 import apriltag errors

### ISSUE THREAD

**Issue by n-gineer** [AprilRobotics/apriltag#125]
I'm using the basic Python example shown in https://github.com/AprilRobotics/apriltag/blob/master/apriltag_detect.docstring.

I created a new file and named it apriltag3_sample.py, it's contents are below: 
(I only changed the imagepath from the example)
```python import cv2 
import numpy as np
from apriltag import apriltag
imagepath = '/home/pi/apriltag/test_files/image.jpg'
image     = cv2.imread(imagepath, cv2.IMREAD_GRAYSCALE)
detector = apriltag("tag36h11")
detections = detector.detect(image)
print("Saw tags {} at\n{}". \
        format([d['id']     for d in detections],
                np.array([d['center'] for d in detections])))
```

when trying to run with 
`python apriltag3_sample.py`
it returned:
```Traceback (most recent call last):
  File "apriltag3_sample.py", line 7, in <module>
    detector = apriltag("tag36h11")
TypeError: 'module' object is not callable
```

**Comment by mkrogius** [comment]
This is odd. What this means is that the symbol 'apriltag' at this point in your code is a module not a class. But it should be a class because the script imports it as 'from apriltag import apriltag'.

Can you run the following python script and report the results? It will mostly likely give an error, that's ok, just report the error too.

```
import apriltag
print('Testing apriltag')
print(type(apriltag))
print(dir(apriltag))
print(apriltag.__file__)

from apriltag import apriltag
print('Testing apriltag.apriltag')
print(type(apriltag))
print(dir(apriltag))
print(apriltag.__file__)

print('Testing apriltag.apriltag.apriltag')
print(type(apriltag.apriltag))
print(dir(apriltag.apriltag))
print(apriltag.apriltag.__file__)
```

**Comment by mkrogius** [comment]
That is odd. What this means is that the name 'apriltag' is a module instead of a class at that line in your code, but it should be a class because of the import line 'from apriltag import apriltag'.

Can you run the following python script and report the results?

**Comment by n-gineer** [comment]
ran and returned:
`Testing apriltag
<class 'module'>
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
None
Testing apriltag.apriltag
<class 'module'>
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'apriltag']
/home/pi/.virtualenvs/cv/lib/python3.7/site-packages/apriltag/apriltag.cpython-37m-arm-linux-gnueabihf.so
Testing apriltag.apriltag.apriltag
<class 'type'>
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'detect']
Traceback (most recent call last):
  File "apriltag/troubleshoot_125.py", line 16, in <module>
    print(apriltag.apriltag.__file__)
AttributeError: type object 'apriltag' has no attribute '__file__'`

**Comment by mkrogius** [comment]
Thanks!

It looks like the problem is that your apriltag.cpython-37m-arm-linux-gnueabihf.so file got installed in a different location than normal. It ended up in python3.7/site-packages/apriltag/apriltag.cpython-37m-arm-linux-gnueabihf.so instead of python3.7/site-packages/apriltag.cpython-37m-arm-linux-gnueabihf.so

The easy fix is just to move the apriltag.cpython-37m-arm-linux-gnueabihf.so file up one level. The better fix is to figure out why the install location from the makefile is incorrect on your machine.

**Comment by n-gineer** [comment]
> Thanks!
> 
> It looks like the problem is that your apriltag.cpython-37m-arm-linux-gnueabihf.so file got installed in a different location than normal. It ended up in python3.7/site-packages/apriltag/apriltag.cpython-37m-arm-linux-gnueabihf.so instead of python3.7/site-packages/apriltag.cpython-37m-arm-linux-gnueabihf.so
> 
> The easy fix is just to move the apriltag.cpython-37m-arm-linux-gnueabihf.so file up one level. The better fix is to figure out why the install location from the makefile is incorrect on your machine.

I wasn't completely clear on the "Install" section of the ReadMe, but was this:

"
If you have CMake installed or it is not difficult to install, then do:
```
$ cmake .
$ sudo make install 
```
"
supposed to be done in "python3.7/site-packages/" or inside of "python3.7/site-packages/apriltag/"?

**Comment by mkrogius** [comment]
No, both of these should be done from wherever you cloned the git repo.

**Comment by n-gineer** [comment]
> No, both of these should be done from wherever you cloned the git repo.
I had cloned into 
`python3.7/site-packages/apriltag/`
and ran cmake & make there. Would this have caused the problem?

**Comment by mkrogius** [comment]
Yes, that is the problem. It will work properly if you clone the git repo pretty much anywhere else

**Comment by brmarkus** [comment]
> import cv2 import apriltag import numpy as np import serial import time
> 
> detector = apriltag.apriltag( family='tag36h11', threads=4, maxhamming=1, decimate=2.0, blur=0.0, refine_edges=True, debug=False )
> 
> when i run the following program which i written it shows an error like this
> 
> Traceback (most recent call last): File "/home/lambda3/My_Workspace/Office_Work/AGV_Projects/Python_Projects/53am23ed_Motor_gets_stopped_based_on_Logitech_camera/captures_tagid_sends_cmd_to_pi.py", line 7, in detector = apriltag.apriltag( ^^^^^^^^^^^^^^^^^ AttributeError: module 'apriltag' has no attribute 'apriltag'

Have a look into the example from the documentation under
https://github.com/AprilRobotics/apriltag?tab=readme-ov-file#python

```
import cv2
import numpy as np
from apriltag import apriltag

imagepath = 'test.jpg'
image = cv2.imread(imagepath, cv2.IMREAD_GRAYSCALE)
detector = apriltag("tagStandard41h12")

detections = detector.detect(image)
```

Would that work for you @harishkumar0004 ?
