### ISSUE TITLE
install errors with pywrap after deleting tagCircle49h12, tagCustom48h12, tagStandard52h13

### ISSUE THREAD

**Issue by n-gineer** [AprilRobotics/apriltag#126]
The Readme at top of repository recommends deleting the header and .c file for each of these families to save on build time. However, doing so breaks numerous files during install preventing building until they are commented out:

apriltag_pywrap.c: 
lines 14,15,17, 25-28

apriltag_demo.c:
lines 45,46,48,94,98,100,256,260,262

opencv_demo:
lines 38,39,41,88,92,94,170,174,176

I'd be happy to turn this into a pull request if someone can help me with a recipe for #ifdef or similar implementation.

**Comment by mkrogius** [comment]
A recent change has improved the speed of the build a lot, so i've removed the instructions to delete those files.
