### ISSUE TITLE
problem with find marker

### ISSUE THREAD

**Issue by sars-ivan-by** [AprilRobotics/apriltag#129]
I get error :WRN: Matrix is singular.
Error, more than one new minimum found.
![pic10](https://user-images.githubusercontent.com/62890514/106292708-30329000-625e-11eb-88b6-546b2274499f.jpg)

this is my code `detector=apriltags3.Detector(quad_decimate=1,decode_sharpening=1)
images,coordinats=division_of_img(img_cv)
for img in images:
imgs,c=division_of_img(img)
i+=1
j=0
for imm in imgs:
j+=1
detections = detector.detect(imm, estimate_tag_pose=True,camera_params=[fx,fy,cx,cy],tag_size=60)
# detections2 = detector2.detect(imm,estimate_tag_pose=True,camera_params=[fx,fy,cx,cy],tag_size=90)
`
I divided imagine for find without error "too many borders" because I don't want use any quad_contours

**Comment by mkrogius** [comment]
Closing since this is about the duckietown python wrapper. In particular I think that that repo is probably using an outdated version of apriltag3
