### ISSUE TITLE
problem with find markers

### ISSUE THREAD

**Issue by sars-ivan-by** [AprilRobotics/apriltag#130]
i get error : Error, more than one new minimum found.
malloc(): mismatching next‑>prev_size (unsorted)
![pic7](https://user-images.githubusercontent.com/62890514/106293340-f0b87380-625e-11eb-9c34-8be181e6daad.jpg)
`detector = apriltags3.Detector()
    detector_2 = apriltags3.Detector(families='tag25h9')
    fx=mtx[0][0]
    fy=mtx[1][1]
    cx=mtx[0][2]
    cy=mtx[1][2]
    detections = detector.detect(img_cv_gray,estimate_tag_pose=True,camera_params=[fx,fy,cx,cy],tag_size=90)
    detections_2 = detector_2.detect(img_cv_gray,estimate_tag_pose=True,camera_params=[fx,fy,cx,cy],tag_size=90)`

**Comment by mkrogius** [comment]
It looks like you aren't using the python wrapper from this library? Whose apriltag code are you using?

**Comment by sars-ivan-by** [comment]
I use this https://github.com/duckietown/apriltags3-py code. What python wrapper did you mean?

**Comment by nzjrs** [comment]
> I use this https://github.com/duckietown/apriltags3-py code. What python wrapper did you mean?

the python wrapper in this repository...

**Comment by sars-ivan-by** [comment]
@nzjrs can you link on python wrapper?

**Comment by nzjrs** [comment]
> @nzjrs can you link on python wrapper?

https://github.com/AprilRobotics/apriltag#install (read the part about python)

**Comment by mkrogius** [comment]
I'm closing this issue since it doesn't happen when using the python wrapper from this repo.
