### ISSUE TITLE
Issue reading older version of 25h7 family tags

### ISSUE THREAD

**Issue by kshitijminhas** [AprilRobotics/apriltag#139]
Hi,

We have 25h7 April tags generated by an older version of the apriltags repo. This is how old version of 25h7 id=0 looks:
![25h7_0](https://user-images.githubusercontent.com/19431579/112033152-8233bb80-8b13-11eb-903b-c654170befaf.jpg)

We would like to detect these tags using the V3 (latest) version of this repository.

To do so, we first generated 25h7 family code using the latest [apriltag-generation](https://github.com/AprilRobotics/apriltag-generation) repo by running the command: `java -cp april.jar april.tag.TagFamilyGenerator custom_9 7`

Apriltag-generator also creates sample 25h7 tags. This is how V3 version of 25h7 id=0 looks:
![screenshot_25h7_new_0](https://user-images.githubusercontent.com/19431579/112033939-506f2480-8b14-11eb-8bbe-95ddcbe57aad.png)

Clearly, these tags are not the same. However, according to [this github issue](https://github.com/AprilRobotics/apriltag-generation/issues/4#issuecomment-627521885) new code is backward compatible and should be able read both old and new tags.

That doesn't seem to be the case for us, V3 repository is able to read the new generated 25h7 tags, but not the old ones.

Thoughts?

Attached are the relevant c files from old a new repos:
[new_tag25h7.c.txt](https://github.com/AprilRobotics/apriltag/files/6184242/new_tag25h7.c.txt)

[old_AprilTags_Tag25h7.h.txt](https://github.com/AprilRobotics/apriltag/files/6184250/old_AprilTags_Tag25h7.h.txt)

Thank you

**Comment by mkrogius** [comment]
Running that command is not going to re-create the same family. This is because the details of tag family generation have changed somewhat. But we make it easy to still use the old families. Just like with Tag36h11.java, you can create a java file representing any old family by putting in the codes for the old family. Here is Tag25h7: https://gist.github.com/mkrogius/6072a324dd901195fea5e80c1a04b2a5
