### ISSUE TITLE
detect tags with encroaching black squares

### ISSUE THREAD

**Issue by berndpfrommer** [AprilRobotics/apriltag#141]
Calibration boards often have encroaching black squares like here:
https://github.com/ethz-asl/kalibr/wiki/calibration-targets
These squares are useful because they allow for corner refinement to reduce corner location errors.

Since the UMich Apriltag detector does not work with such tags, people typically use Michael Kaess' implementation for that:
https://bitbucket.org/kaess/apriltags/src/master/
But that one is no longer actively maintained.

Question: is there a way to get the UMich Apriltag3 detector to work in such situations? Where exactly in the detection algorithm does it fail? Any suggestions on how this could be improved?
Thanks!

**Comment by mkrogius** [comment]
The switch from AprilTag 1 -> AprilTag 2 changed how the quadrilateral detection works. What the more modern detector looks for is a contiguous white region that neighbors/encloses/is enclosed by, a contiguous black region. Those extra squares are splitting the white border into multiple disconnected elements, so the tag detection will fail at a pretty fundamental level.

AprilTag 3 has a solution for this problem, which I haven't seen anyone use yet. We now allow tag families which have the black border on the outside, and the white border on the inside. So you could make a new sort of checkerboard, which has alternating tags from two different families, the classic 36h11 family, and a new 36h11 family with the borders reversed. This would be fully detectable by the AprilTag 3 detector.

**Comment by berndpfrommer** [comment]
Alright then, no easy fix.
Making a calibration board as you described is indeed an interesting idea that I may try out. The drawbacks are that I'd have to upgrade my calibration boards and that Kalibr, which is no longer actively maintained, will not work with the new boards. Still thanks for your prompt reply!

**Comment by reprojection-calibration** [comment]
Hi guys! @mkrogius I took inspiration from this thread, particularly the part where you wrote "We now allow tag families which have the black border on the outside, and the white border on the inside." and designed a Kalibr like april grid which works with the current AprilTag3 detector. However instead of using two families like you suggested I just use one family and insert the black squares just like Kalibr did. 

You can see the targets here (called Aprilgrid3) in  [my readme](https://github.com/reprojection-calibration/reprojection#calibration-target-types) and the "family" code [here](https://github.com/reprojection-calibration/reprojection/tree/main/code/library/feature_extraction/src/generated_apriltag_code).

**Comment by reprojection-calibration** [comment]
Link to a small wiki article with some more details: https://github.com/reprojection-calibration/reprojection/wiki/Aprilgrid3

**Comment by berndpfrommer** [comment]
> Hi guys! [@mkrogius](https://github.com/mkrogius) I took inspiration from this thread, particularly the part where you wrote "We now allow tag families which have the black border on the outside, and the white border on the inside." and designed a Kalibr like april grid which works with the current AprilTag3 detector. However instead of using two families like you suggested I just use one family and insert the black squares just like Kalibr did.
> 
> You can see the targets here (called rightly go Aprilgrid3) in [my readme](https://github.com/reprojection-calibration/reprojection#calibration-target-types) and the "family" code [here](https://github.com/reprojection-calibration/reprojection/tree/main/code/library/feature_extraction/src/generated_apriltag_code).

That is a really neat idea. Do you also have a handly little python code to generate the boards?

**Comment by reprojection-calibration** [comment]
@berndpfrommer unfortunately I do not have a python script or any really nice way to create arbitrary boards. In the readme I [link](https://github.com/reprojection-calibration/reprojection#aprilgrid3-target-files) to three I made.

I have a test in the library where I generate an Aprilboard3 [see link](https://github.com/reprojection-calibration/reprojection/blob/3b59f2e3dc35753aef6fa01bb8c71b1135caefb2/code/library/feature_extraction/src/target_generators.test.cpp#L43), but getting that up and running might be more effort than it is worth and provide you less flexibility than you want.

**Comment by mkrogius** [comment]
Very cool! I'm glad this exists
