### ISSUE TITLE
Pose estimation without distortion coefficients?

### ISSUE THREAD

**Issue by xfunctor** [AprilRobotics/apriltag#146]
**Describe the bug**
I want to use apriltag to do accurate pose estimation (i.e. pose of the tip of a manipulator). 
It seems that you only use intrinsic matrix without distortion coefficients. If the camera suffers from severe distortion, will the pose estimation lose accuracy?

```C
// First create an apriltag_detection_info_t struct using your known parameters.
apriltag_detection_info_t info;
info.det = det;
info.tagsize = tagsize;
info.fx = fx;
info.fy = fy;
info.cx = cx;
info.cy = cy;

// Then call estimate_tag_pose.
apriltag_pose_t pose;
double err = estimate_tag_pose(&info, &pose);
// Do something with pose.
...
```

**Comment by mkrogius** [comment]
That is correct. There are two solutions here:
1) Rectify the image before passing it to apriltag detection & pose estimation.
2) After apriltag detection but before pose estimation, rectify the detected tag corner locations. Then do pose estimation with the rectified corner locations.
