### ISSUE TITLE
How to select a camera HW to improve the accuracy?

### ISSUE THREAD

**Issue by Momohanfeng** [AprilRobotics/apriltag#160]
How to select a camera to improve the accuracy on robot?  Are there some rules to follow? 
I have 2 situations on apriltag:
1st. Robot will run auto-docking by watching tag. 
2nd. mechanical arm will catch the target by recognizing tag.

**Comment by mkrogius** [comment]
As far as the hardware goes, the more pixels and imaging clarity the better. Although, more pixels will also result in increase processing time.
