### ISSUE TITLE
UWP arm64 support

### ISSUE THREAD

**Issue by artificial-jamesirei** [AprilRobotics/apriltag#163]
Hello!  I am trying to use Apriltags on a Hololens 2 application and I am a little new to all of this..basically I am trying to generate a dll that is for ARM64 UWP and I'm not really sure where to start.  Thank you!

**Comment by christian-rauch** [comment]
Windows support was added with https://github.com/AprilRobotics/apriltag/pull/27. Other than this, we cannot support generic Windows questions.
