### ISSUE TITLE
is there any possible to make apriltag detect more faster?

### ISSUE THREAD

**Issue by jcyhcs** [AprilRobotics/apriltag#164]
hi,professor!:

thank for your job!  is there any possible to let apritag detect more faster? for example use GPU? so i could deal with 2K,4K image resolutions, it is very helpful! so please help!

**Comment by mkrogius** [comment]
Does this part of the user guide help? https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#increasing-speed

**Comment by jcyhcs** [comment]
emm, i have 6 threads with my 6cores cpu, but i test apriltag detection time also have ~40ms with an image 2592x1944, it not fast enough, so,professor? can you improve it to about ~30ms？ please！

**Comment by mkrogius** [comment]
What settings are you using for nthreads and quad_decimate?
