### ISSUE TITLE
Which family and tag shape should I choose for the minimal location and rotation error?

### ISSUE THREAD

**Issue by tachikoma777** [AprilRobotics/apriltag#173]
Hi, I have a question about choose the proper tag famliy and tag shape,  I need to minimal location and rotation error in 2-3m range. Only 10 tags is needed or less. The tag can be print on A3 or A4 paper. Is there a best opinion?
Also I wonder if apriltag only use four lines to get four corners for location and rotation estimation? Does this mean a complex tag (with complex corner) won't get higher accuracy?

Thanks!

**Comment by mkrogius** [comment]
Start with the tagStandard41h12 family, print as large as will fit on your paper.
