### ISSUE TITLE
Not stable for tag16h5?

### ISSUE THREAD

**Issue by libing64** [AprilRobotics/apriltag#180]
**Describe the bug**
The detection result is not stable, is that a bug? 

![Screenshot from 2021-11-09 19-48-18](https://user-images.githubusercontent.com/3192355/140921827-dae8cee2-cd3b-4f89-8fe2-056578559fc0.png)

**To Reproduce**
```
./opencv_demo -f tag16h5
```

```
        imshow("Tag Detections", frame);
        char key = waitKey(30);
        if (key == 'q')
            break;
```

**Expected behavior**

** Input Image**
If applicable, please attach the input image that reproduces the problem.

**Screenshots**

**Operating Sytem**
[e.g. Ubuntu, iOS, Windows]

** Installation Method**
[e.g. I built AprilTag from source following the instructions in the README]

** Code version **
What does the version tag in package.xml say? Or, if you have downloaded the code from github right now, say current github HEAD.

**Additional context**

**Comment by mkrogius** [comment]
It is most likely not a bug. The tag16h5 family has an extremely high false positive rate compared to the other tag families

**Comment by libing64** [comment]
@mkrogius Are there any suggestions to optimize this problem?

**Comment by mkrogius** [comment]
I suggest using a different tag family. Either tagStandard41h12 or tag36h11

**Comment by libing64** [comment]
> I suggest using a different tag family. Either tagStandard41h12 or tag36h11

Got it, great thanks.
