### ISSUE TITLE
Hello, The tag I use is Tag36H11. does the size of the tag directly measure the outer boundary? Or what else?

### ISSUE THREAD

**Issue by Zhang-Qinghui** [AprilRobotics/apriltag#185]
**I use the measured distance D as the size of the tag as shown in the figure. Is this right?**

![1638792333267](https://user-images.githubusercontent.com/49428118/144843113-99658802-fdf7-458b-b410-621270ba166f.jpg)

**Comment by christian-rauch** [comment]
Yes, that's correct.

But please, ask such questions on https://stackoverflow.com. We try to keep "issues" only for issues with the library, not for general usage questions.

**Comment by Zhang-Qinghui** [comment]
OK, I see. Thank you for your reply.
