### ISSUE TITLE
No quad detection after seemingly good cluster detection

### ISSUE THREAD

**Issue by huberya** [AprilRobotics/apriltag#190]
Hi
I've been using Apriltag2 for a while now, with a detector from ASL and wanted to switch to Apriltag3 and using the built in detector.

Note that I use a two pixel border for the 36h11 family and thus applied the "hack" proposed in #45.

I turned on "debug" and set  "quad_decimate" to 1.0 and also varied a bit with the "blur" without success.

My initial image is:
![und_img_7452_1637932705 105134](https://user-images.githubusercontent.com/22527913/146452606-d1eac1db-4652-491b-84fe-654b4d9537fd.jpg)

The clusters image still looks good from what I understand:
![Screenshot from 2021-12-16 22-37-38](https://user-images.githubusercontent.com/22527913/146452750-5230575b-828a-4962-bb5e-323bebb95a33.png)

But then the in the next output, if I followed the code correctly it seems to discard all quads (debug_quads_raw):
![Screenshot from 2021-12-16 22-39-09](https://user-images.githubusercontent.com/22527913/146453016-1bf5122e-3e35-46ba-a18d-ba417e2515a6.png)

Any ideas on why this happens or what I could do to achieve better detections.

Thanks already for your help

**Comment by mkrogius** [comment]
This setup was supported in AprilTag 1, but not Apriltag 2 or 3. See https://github.com/AprilRobotics/apriltag/issues/141 for details/discussion

**Comment by huberya** [comment]
Ah I did not see that, thanks
