### ISSUE TITLE
deep learning method for apriltag? it working well?

### ISSUE THREAD

**Issue by jcyhcs** [AprilRobotics/apriltag#192]
hi,professor:
in 2021, there is a paper called deeptag, which said can detect apriltag, more accurate, github:https://github.com/herohuyongtao/deeptag-pytorch
is this method work? it use python, which not easy for engineering application
what think about it? please help!

**Comment by christian-rauch** [comment]
I am going to close this as this is unrelated to this library. If you have questions about the performance of different AprilTag-libraries, you better ask at https://robotics.stackexchange.com.
