### ISSUE TITLE
Estimate camera pose from detected apriltag's pose

### ISSUE THREAD

**Issue by gft-ai** [AprilRobotics/apriltag#193]
Hi guys, thank you for your amazing work.

I am trying to localise my robot using apriltags. So right now I can get the pose of the detected tag but I am not sure how to calculate the pose of the camera which is attached on my robot from it.

 Could anyone point me in the right direction please?

Thanks a lot!

**Comment by christian-rauch** [comment]
The AprilTag pose is the transformation from your camera optical frame to the tag frame. The camera pose with respect to the AprilTag frame is then just the inverse.

**Comment by gft-ai** [comment]
> The AprilTag pose is the transformation from your camera optical frame to the tag frame. The camera pose with respect to the AprilTag frame is then just the inverse.

Oh great, I just realised I am actually using your implementation (apriltag_ros) for ROS2.

So would that mean I would have to inverse the homography matrix and multiply that with the 3d translation of the apriltag' pose?

I apologies if this is a very basic and dumb question.

**Comment by gft-ai** [comment]
Great. Thank you so much for your help!
