### ISSUE TITLE
Is there a simple way to use estimate_tag_pose with only corners & center?

### ISSUE THREAD

**Issue by VincentMarnier** [AprilRobotics/apriltag#200]
Hello,
This might be out of your scope, so if you won't answer this, I can definetly understand.

I have been playing with apriltag a lot lately; I also browsed your code quite a bit; yet some concepts are still strange to me.
I have a small AR project I am doing in order to learn a bit more about computer vision.
So far I successfuly combined AprilTag with ARCore and I performs some minor AR things.
In this very same project I thought it would be cool to combine QRCodes with ARCore's SLAM. 
To do so I have to estimate the QRCode pose in the 3D environment.
I thought "apriltag already can do that, I could just re-use its implementation".
And that's when things got out of hands.

So, after days of trying to achieve just that, I am finaly asking for help as it is beyond my understanding.
What I did until now is:
1. I make a fake apriltag_detection_info_t pointing to a fake apriltag_detection_t which has:
    - family = null
    - id = 0
    - hamming = 2
    - decision_margin = 1f
    - H = 3x3 identity matrix
    - c = QRCode's center
    - p = QRCode's corners
2. I call `estimate_tag_pose` with my fake data
3. Then I draw a debug rect to see where my tag is positioned

The returned position & rotation is not the one I would've expected.
I assume, H should not be an identity matrix; I tryed a lot of things browsing apriltag's code, yet never got a right output.

Is there a simple way to do this?

Thanks in advance for your time and kindness

**Comment by christian-rauch** [comment]
Homography is the transformation between two image planes. In the case for AprilTags, this is a transformation from an ideal plane only containing the AprilTag with an edge size of 1, to the plane of the real AprilTag in the image.

If you don't need the AprilTag detection, I would recommend just use OpenCV. The OpenCV page on [Homography](https://docs.opencv.org/4.5.5/d9/dab/tutorial_homography.html) has some explanations and API examples (e.g. for `findHomography`). Once you have the Homography matrix, you can compute the pose as I did in my node https://github.com/christianrauch/apriltag_ros/blob/2.1.0/src/AprilTagNode.cpp#L158-L190.
