### ISSUE TITLE
python wrapper for estimate_tag_pose

### ISSUE THREAD

**Issue by ZhengWang26** [AprilRobotics/apriltag#237]
this is an extension to a previous issue [#101](https://github.com/AprilRobotics/apriltag/issues/101)

I looked at `sitepackages/apriltag.py` and under `Detector` class I found `detection_pose()` function that calls a cpp function with `pose_from_homography()`, which looks like `estimate_tag_pose` but I'm not 100% cerntain.
I didn't find any extra documentation describing what `detection_pose()` does. 

**Can someone clarify that this is indeed a wrapper for `esimate_tag_pose()`?**

![Screenshot from 2022-06-21 17-20-36](https://user-images.githubusercontent.com/44683126/174899346-9b045dce-8272-43fe-8fe0-030ec86d1ff7.png)

Also the pose result from `detection_pose()` is a 4 by 4 matrix. How do I interprete this matrix? 

**Is it in the form of**
[ R00 R01 R02 TX ]
[ R10 R11 R12 TY ]
[ R20 R21 R22 TZ ]
[ 0   0   0   1  ]

![ori_lib](https://user-images.githubusercontent.com/44683126/174899884-fe80597e-ffd0-4269-920f-103e1e156501.png)

**Comment by christian-rauch** [comment]
Please post the raw text with markdown formatting and syntax highlighting in future.

Are you talking about the python wrapper in this very repository? There is no file `apriltag.py` or a reference to `pose_from_homography`. You may refer to https://pypi.org/project/apriltag/, which is not related to this repo. Please open an issue in their repo (https://github.com/swatbotics/apriltag) if you need support with their Python wrapper.
