### ISSUE TITLE
Is it possible to speed up April Tag detection using the GPU?

### ISSUE THREAD

**Issue by Hiroaki-K4** [AprilRobotics/apriltag#242]
Hi, thank you for sharing the code.
I have a question.
Is it possible to speed up April Tag detection using the GPU?
Thanks!

**Comment by christian-rauch** [comment]
Maybe, if someone implements it. But this would probably result in a different "apriltag library". I am closing this as it is not really relevant to this repo.

If someone is implementing this, create a PR to this repo. But I am not sure it will be accepted as it is quite a big change and there are not many maintainers that will have the time to review such changes that will have a big impact.

**Comment by AustinSchuh** [comment]
I haven't had time to try to pull the code out into an easily distributed set of classes and contribute it back, but https://github.com/frc971/971-Robot-Code/tree/master/frc971/orin implements an april tag detector in CUDA which matches the algorithms and results quite close to how this repo does.  I made design decisions to make it faster which limit the number of pixels in an image to 4^20.  I'm seeing a ~5-10x speedup on my images images on an Orin NX 8GB, and a RTX 3080 TI.
