### ISSUE TITLE
memory leak when use "estimate_tag_pose"

### ISSUE THREAD

**Issue by why-freedom** [AprilRobotics/apriltag#253]
**Describe the bug**
when i use estimate_tag_pose, the memory grow up slowly,  I use opencv_demo.

# my code
            apriltag_detection_info_t *info = (apriltag_detection_info_t *)calloc(1, sizeof(apriltag_detection_info_t));
            apriltag_pose_t *pose = (apriltag_pose_t *)calloc(1, sizeof(apriltag_pose_t));
            info->det = det;
            info->tagsize = 0.1;
            info->fx = 387.852;
            info->fy = 387.586;
            info->cx = 319.157;
            info->cy = 235.818;

            info->det = det;
            double err = estimate_tag_pose(info, pose);

# result
time, pid, cpu, memory
21:56:20,6330,104,48.1016,
21:57:20,6330,103,48.3594,
21:58:21,6330,103,48.875,
21:59:21,6330,103,49.1328,
22:00:21,6330,104,49.6484,
22:01:21,6330,104,49.9062,
22:02:21,6330,103,50.1641,
22:03:21,6330,103,50.4219,
22:04:21,6330,103,50.9375,
22:05:21,6330,104,51.1953,
22:06:21,6330,104,51.7109,
22:07:21,6330,104,51.9688,

**Operating Sytem**
Ubuntu18.04
** Installation Method**
source README, cmake .. make 
** Code version **
use master

**Comment by christian-rauch** [comment]
Are you using the `opencv_demo` or your own code? Just from your code, I can tell that you have to free `info` and `pose`.

1. Can you run this with ASAN and valgrind and report back any memory issues?
2. Can you provide a complete example (code, build script, input data) to reproduce this?

**Comment by why-freedom** [comment]
> Are you using the `opencv_demo` or your own code? Just from your code, I can tell that you have to free `info` and `pose`.
> 
> 1. Can you run this with ASAN and valgrind and report back any memory issues?
> 2. Can you provide a complete example (code, build script, input data) to reproduce this?

# Code

**Comment by why-freedom** [comment]
I slove the problem, thank you!

**Comment by wxmerkt** [comment]
Thanks for the update - can you please confirm what the problem was?
