### ISSUE TITLE
Help with thresholding parameters

### ISSUE THREAD

**Issue by naiveHobo** [AprilRobotics/apriltag#292]
**Describe the bug**
In my use case, I come across several such instances where there are odd lighting conditions and/or shadows on the tags in the environment. Looking at the debug images, this particular tag seems to be thresholding well and there's a decent enough cluster around the tag. However, this tag is never detected as a candidate quad. I'm using this image as a general example but there are several instances where I come across such situations. What can be done to make this situation better?

**To Reproduce**
Run apriltag_demo on the attached input image with the following parameters:
```cpp
td->nthreads = 1;
td->quad_decimate = 0.0;
td->quad_sigma = 0.0;

td->qtp.max_nmaxima = 10;
td->qtp.min_cluster_pixels = 5;

td->qtp.max_line_fit_mse = 10.0;
td->qtp.cos_critical_rad = cos(10 * M_PI / 180);
td->qtp.deglitch = false;
td->qtp.min_white_black_diff = 5;

td->refine_edges = true;
td->decode_sharpening = 0.25;
```

**Expected behavior**
At least a quad to be detected around the tag in the image, decoding is not as big an issue.

**Input Image**
![test13](https://github.com/AprilRobotics/apriltag/assets/22402940/464348c1-3299-400c-8907-271f70722690)

**Screenshots**

**debug_threshold**
![debug_threshold](https://github.com/AprilRobotics/apriltag/assets/22402940/42c370fe-e856-4322-8802-bdd776f90786)

**debug_segmentation**
![debug_segmentation](https://github.com/AprilRobotics/apriltag/assets/22402940/75dbe9de-6f69-47ab-abb2-96da437c9ff3)

**debug_clusters**
![debug_clusters](https://github.com/AprilRobotics/apriltag/assets/22402940/cb430959-2a10-4ceb-89eb-a929b799d3b2)

**debug_quads_raw**
![debug_quads_raw](https://github.com/AprilRobotics/apriltag/assets/22402940/1c344a1a-9254-475b-aa5d-49f5ddbf8300)

**Operating Sytem**
Ubuntu 20.04

**Installation Method**
I built AprilTag from source following the instructions in the README

**Code version**
3.3.0

**Comment by christian-rauch** [comment]
I guess that this is essentially the same issue as https://github.com/AprilRobotics/apriltag/issues/161 and https://github.com/AprilRobotics/apriltag/issues/235. To cite https://github.com/AprilRobotics/apriltag/issues/161#issuecomment-881967591:
> The reason the tag on the right is not detected is because of the sharp lighting gradient on the bottom left corner. This causes the adaptive thresholding (see debug_threshold.pnm) to classify a chunk of the white border as black, which causes the derived edge (see debug_clusters.pnm) to loop all the way back around the outside of the tag.

Without changing the thresholding implementation in the apriltag library you have to preprocess the image to better separate the black/white content of the tag.

You may also get lucky with decimation and blurring:
```
./apriltag_demo -d -x 4 -b 2 270263675-464348c1-3299-400c-8907-271f70722690.pnm
```
gives me one detection:
```
detection   0: id (36x11)-37  , hamming 1, margin  186.443
```
but not a good edge alignment for the quad:
![debug_output](https://github.com/AprilRobotics/apriltag/assets/8226248/63cfee10-8859-450c-a18c-16d312f7c343)
