### ISSUE TITLE
Problem About the Adaptive Threshold

### ISSUE THREAD

**Issue by Hxybit** [AprilRobotics/apriltag#30]
Hi,
I am glad to find this version shows the in-process pictures, it helps me a lot for learning this algorithm.
In the article ‘AprilTag 2: Efficient and robust fiducial detection’ fig.3 (b), the adaptive threshold result seemed normal. When I test the opencv demo, results are as follows. The right is the source picture, the left used another  algorithm to threshold, and put into detector. 
It looks so many noises and candidate quads when using threshold algorithm on the demo , so is this to save time or for precision?
Thanks!

![issue](https://user-images.githubusercontent.com/29997345/56419776-0cdb6280-62ce-11e9-8242-a87d243ff970.png)

**Comment by mkrogius** [comment]
It looks like adaptive thresholding is performing particularly poorly here. Can you send me your source picture in full resolution?

On high resolution images where you do not care about detecting extremely small (apparent size of ~25px by 25px) tags then it is a good idea to downscale the source image before passing it to the detector.

**Comment by Hxybit** [comment]
Thanks for your reply!
Effect of adaptive threshold should not much relationship with resolution. Your answer is enough for me to learn AprilTags, and the performance of the detector looks very good in test. Of course the video pipeline was in lower resolution.
![IMG_5042](https://user-images.githubusercontent.com/29997345/56456693-5f864e80-63a2-11e9-9a73-c85c75ee1388.JPG)

**Comment by mkrogius** [comment]
Hi, if the detector is now working as expected, would you please mark this issue as closed?

Thanks,
Max
