### ISSUE TITLE
#include issues when building from "make install" locations

### ISSUE THREAD

**Issue by UberEclectic** [AprilRobotics/apriltag#31]
After building apriltag the usual way, then following with "make install" I am trying to compile code from outside the apriltag build area, and am relying on "`pkg-config --cflags --libs apriltag`" in my makefile.

The use of "make install" from the apriltag cmake+make means that the include files from /usr/local/include/apriltag are in play, not the ones from the original apriltag build area.

As a result I ran into issues with two include files that needed modifications.
The following ones were problematic (likely there are more):

    /usr/local/include/apriltag/common/getopt.h
    /usr/local/include/apriltag/common/string_util.h

Both files reference nearby include files only with "filename.h" instead of <apriltag/common/filename.h" ...

I had to modify the above two files, and there are likely others that suffer from this same problem.

Here are the diffs:

$ diff /usr/local/include/apriltag/common/getopt.h

    /usr/local/include/apriltag/common/getopt.h_broken
    30,31c30,31
    < #include <apriltag/common/zarray.h>
    < #include <apriltag/common/string_util.h>
    ---
    > #include "zarray.h"
    > #include "string_util.h"

$ diff /usr/local/include/apriltag/common/string_util.h

    /usr/local/include/apriltag/common/string_util.h_broken
    35c35
    < #include <apriltag/common/zarray.h>
    ---
    > #include "common/zarray.h"

Someone way smarter than me can probably figure out how to fix these (and others) properly so that the #include references will work during the initial build and later on in other sources that reference the "make install" versions under /usr/local/include/apriltag.

**Comment by mkrogius** [comment]
Thanks for the report, it should be fixed now.
