### ISSUE TITLE
Planned Python Package Index (PyPI) package?

### ISSUE THREAD

**Issue by Jgunde** [AprilRobotics/apriltag#322]
There are lots of other AprilTag packages on PyPi that can be installed easily with pip. But none of them seem as robust and well maintained as this one. Is it possible to install this library with pip?

**Comment by christian-rauch** [comment]
Not at this moment. Someone would need to create a Python project description (`pyproject.toml`) or similar to generate a wheel file from the source.

**Comment by Jgunde** [comment]
Ok thank you!

**Comment by sgbaird** [comment]
@christian-rauch if I were to take a shot at this, is there a possibility of getting this integrated into the main project?

**Comment by christian-rauch** [comment]
Sure. If you add a CMake target that generates the wheel file or similar, you can send a PR for review.

If you need a starting point for this, I suggest https://github.com/stevenlovegrove/Pangolin as it has a CMake target that builds the wheel file (`cmake --build build -t pypangolin_wheel`).
