### ISSUE TITLE
How to detect  AprilGrid? 

### ISSUE THREAD

**Issue by wfxcqsc** [AprilRobotics/apriltag#328]
hello,I am confused with the AprilGrid, when i detect the following picture（Apriltag board） using the opencv_demo, it can be successfully detected.
![apriltag7](https://github.com/AprilRobotics/apriltag/assets/76416341/2098c267-1d9c-48eb-b27b-f7bec39700b4)

however,when detect the AprilGrid, it can not detect, i guess the reason is the the border width of Apriltag board is one ，while AprilGrid with border width the size of two
![ apriltag3](https://github.com/AprilRobotics/apriltag/assets/76416341/a9fedf08-7a4a-4eb4-b523-f3fd2e025f0d)

so，i want to figure out whether can set the borderbits, and how to detect AprilGrid?

Looking forward to your reply!

**Comment by christian-rauch** [comment]
The apriltag library needs a white border around the tag to do the edge detection properly. This border is interrupted by the black squares on the corner of the tags.

**Comment by wfxcqsc** [comment]
thanks for your reply!
however, i have tried to cover up the black squares in the AprilGrid，and detect again. but it still doesn't work.
![apriltag7](https://github.com/AprilRobotics/apriltag/assets/76416341/024fdd59-d998-4b79-a2a6-392626311480)

then,  i detect the same picture get from the above using OpenCV aruco , there is a"DICT_APRILTAG_36h11", if i don't set the "markBorderBits"(default value is 1), it also can't detect. while i set the parameter "markBorderBits=2", it can be successfully detect 

![image](https://github.com/AprilRobotics/apriltag/assets/76416341/50b40050-13b2-4a06-994e-d5883096faf0)
Therefore, in addition to black square interruption, is the border width also a part of the impact on detection? and whether the apriltag library can detect the APRILGRID?

**Comment by wfxcqsc** [comment]
thanks for your reply!
i am sorry about my issue，i put the wrong image in the first picture. the Apriltag board that can be Apriltag library successfully detect is the following
![untitled](https://github.com/AprilRobotics/apriltag/assets/76416341/e7bf293f-2bf1-49cf-aa27-bf360506408b)

however, i have tried to cover up the black squares in the AprilGrid，and detect again. but it still doesn't work.
![apriltag7](https://github.com/AprilRobotics/apriltag/assets/76416341/c1b66165-be47-4556-aa51-03ca9d482364)

then, i detect the same picture get from the above using OpenCV aruco , there is a"DICT_APRILTAG_36h11", if i don't set the "markBorderBits"(default value is 1), it also can't detect. while i set the parameter "markBorderBits=2", it can be successfully detect
![image](https://github.com/AprilRobotics/apriltag/assets/76416341/0f9310bb-04b5-4a79-984e-cf96bdc73ab3)

Therefore, in addition to black square interruption, is the border width also a part of the impact on detection? and whether the apriltag library can detect the APRILGRID?

**Comment by mkrogius** [comment]
The apriltag library only supports a black border width of 1. It looks like in your image the border width is 2, which is why it is not detected

**Comment by christian-rauch** [comment]
@wfxcqsc I tried your AprilGrid image with `apriltag_demo` and `opencv_demo` and I got a couple of detections. Do you not get any detections?

Alternatively, you can also try the "AprilTags C++ Library" from https://people.csail.mit.edu/kaess/apriltags/ (https://bitbucket.org/kaess/apriltags/src/master/) which generally supports tag families with multiple black border sizes: https://bitbucket.org/kaess/apriltags/src/3aea96d3239bb83870cb5e0a85f142a2b0589563/AprilTags/TagFamily.h#lines-64.

**Comment by wfxcqsc** [comment]
Thanks for your reply！in fact, when I using opencv_demo to detect AprilGrid which have black squares on the corner of tags, I can not detect any detections. but I have detected AprilGrid successfully by using Kalibr，and I will also try the “AprilTags C++ Library”.
