### ISSUE TITLE
ReadMe File Error

### ISSUE THREAD

**Issue by Suave101** [AprilRobotics/apriltag#335]
On the ReadMe file of the project here:
![fix](https://github.com/AprilRobotics/apriltag/assets/57422635/fe86026b-a645-46e6-8936-5da65c40485a)
Perma-Linked: https://github.com/AprilRobotics/apriltag?tab=readme-ov-file#python
The link that I boxed in red is incorrect. It directs you to a repo that is no longer supported. Here is the correct link:
https://github.com/duckietown/lib-dt-apriltags
Here is a picture of the unsupported repo that the link currently links to:
![image](https://github.com/AprilRobotics/apriltag/assets/57422635/f7fabb8d-684c-496d-ae9b-08b58f6a0cdf)

**Comment by Suave101** [comment]
Here is a pull request I made to fix the issue:
#336

**Comment by christian-rauch** [comment]
Fixed via https://github.com/AprilRobotics/apriltag/pull/336.
