### ISSUE TITLE
 fatal error: numpy/arrayobject.h: No such file or directory

### ISSUE THREAD

**Issue by lianghongzhuo** [AprilRobotics/apriltag#49]
while compiling the project using the quick start guide [here](https://github.com/AprilRobotics/apriltag_ros), I encounter the following errors:
```
.../src/apriltag/apriltag_pywrap.c:6:31: fatal error: numpy/arrayobject.h: No such file or directory
compilation terminated.
```
I'm using ubuntu 16.04 and ros kinetic

**Comment by mickeyouyou** [comment]
sudo apt-get install python-numpy

**Comment by lianghongzhuo** [comment]
Thank you for your answer, but this doesn't work. I have python-numpy installed, but the code failed to find it.

**Comment by EpsAvlc** [comment]
> Thank you for your answer, but this doesn't work. I have python-numpy installed, but the code failed to find it.

Have you solved the problem ? I met the error too and don't know how to do with it.

**Comment by lianghongzhuo** [comment]
Check out to the version that did not add python wrapper of apriltag should work.
But this is only a workaround.

**Comment by mkrogius** [comment]
Should be fixed now.

**Comment by thachdo** [comment]
The following command worked for me
```
sudo apt-get install --reinstall python-numpy
```
