### ISSUE TITLE
AprilTags with IR/greyscale images?

### ISSUE THREAD

**Issue by a-price** [AprilRobotics/apriltag#52]
Would you expect to be able to detect tags in an image from an IR camera like the one on the Kinect2? I gave it a try but was unable to get any detections. (See image below for an example.)

![kinect2_victor_head_ir_optical_frame_screenshot_27 07 2019](https://user-images.githubusercontent.com/3324751/61999816-74f0d000-b097-11e9-8abc-468c688ace4d.png)

**Comment by atuleu** [comment]
This project  @formicidae-tracker/artemis  uses high resolution IR camera and apriltag3 to detect ants. There is no issue to use monochromatic images.

Maybe play with the quad detection algorithm parameter. First think to check is how many quads are detected in the image using the nquad field from apriltag_detector_t struct

**Comment by Affie** [comment]
I quickly ran the detector on you image and it picked up 4 tags:
![image](https://user-images.githubusercontent.com/6612981/64430751-377d5a80-d0b9-11e9-9ce9-bf27bea7ead3.png)
