### ISSUE TITLE
Apriltag and accurate angle measurement

### ISSUE THREAD

**Issue by nyanmn** [AprilRobotics/apriltag#58]
Trying to measure the yaw,pitch and roll angle using Apriltag. I have tag size constraint and can't be used more than 6cm.
Now measure the yaw angle and observed some fluctuations and noises.
Which type of tag and approach deliver better accuracy in rotation measurement?

**Comment by mkrogius** [comment]
Sorry I didn't see this at the time. If you can't increase the size of the tag, you can either reduce the distance between the tag and the camera or use a higher-resolution camera.
