### ISSUE TITLE
Is goodness still represented anywhere?

### ISSUE THREAD

**Issue by jbendes** [AprilRobotics/apriltag#69]
Apriltag 2 had a concept of `goodness` defined as a measure of the quality of tag localization - average contrast of the pixels around the border of the tag. Does this concept still exist anywhere?

**Comment by jbendes** [comment]
Additionally there was a `refine_pose` that enabled that computation if that helps shed any light

**Comment by jbendes** [comment]
Is it essentially equivalent to the return of the following?
`double estimate_tag_pose(apriltag_detection_info_t* info, apriltag_pose_t* pose);`

**Comment by mkrogius** [comment]
There is no longer an estimate of goodness. I found that it did not really provide too much information about whether detection was successful or whether the tag's pose was accurate. If you need super accurate tag localizations and want to throw out some detections, it is probably better to use some other heuristic.
