### ISSUE TITLE
Any tips to increase detection rate?

### ISSUE THREAD

**Issue by suraj2596** [AprilRobotics/apriltag#75]
Hi all,

Currently, I'm able to detect tags at 15fps on Pi 4 on 480x480 frames. Though `image_raw` publishes up to 50fps, the `/tag_detection` rate doesn't change even though a lot of RAM is available. Tried overclocking but the detection rate fell down on contrary. And can't really reduce tag sizes anymore.

Other things I tweaked:  
- `tag_decimate` has no effect. 
- Running 4 threads. 
- <will add them over time>

Any advice from your past experiences? 

Thanks!

**Comment by suraj2596** [comment]
EDIT: In order to decimate, `tag_decimate` needs to be increased in value. Silly me, I was doing the opposite.

**Comment by mkrogius** [comment]
Sorry for not responding sooner. Was your effort successful? What frame rate did you achieve?

**Comment by suraj2596** [comment]
Hey! No problem.

Playing with the decimate tag gave up to 30fps. That's pretty decent I suppose.

**Comment by mkrogius** [comment]
Yeah, that's not bad, but neither is it that good. What did you set the decimate factor to?

**Comment by suraj2596** [comment]
Made it 1.5. But on a laptop, I used to get 30fps for default settings. What else can we expect from Pi's limited CPU.
