### ISSUE TITLE
Installation on Anaconda environment

### ISSUE THREAD

**Issue by lixiii** [AprilRobotics/apriltag#77]
I have had some trouble building Apriltag on an Anaconda environment in Ubuntu 18.04

Here is my solution and I hope it helps others: use the following commands to build instead

```
export CONDA_HOME=/opt/conda
export CONDA_ENV=opencv
cmake  -D PYTHON_LIBRARY=$CONDA_HOME/envs/$CONDA_ENV/lib/libpython3.6m.so -D PYTHON_INCLUDE_DIR=$CONDA_HOME/envs/$CONDA_ENV/include/python3.6m .
mkdir -p ~/.local/lib/python3.6/site-packages # the Makefile installs the wrapper to the user-site so make this directory if not exists
sudo make install
``` 

I got this working after consulting https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html which mentions the parameters `PYTHON_LIBRARY` and `PYTHON_INCLUDE_DIR`. Incidentally, these are the same parameters used when one builds OpenCV (probably because both use the same Cmake module). 

If you think this is useful, I could open a pull request incorporating this instruction (see my fork https://github.com/lixiii/apriltag). 

--------

If you are curious, this is the error that you will get if you try installing using `cmake . && make install` and anaconda: 

```
(base) root@47b067de4de5:~/apriltag2# cmake .
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
...
...
-- Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
-- Configuring done
-- Generating done
-- Build files have been written to: /root/apriltag
```

**Comment by christian-rauch** [comment]
I think this issue is related to something missing in your environment (`PYTHON_LIBRARIES`, `PYTHON_INCLUDE_DIRS`) and not the library. Closing this for now.
