### ISSUE TITLE
one question of decode about  intensity model: intensity(x,y) = C0*x + C1*y + CC2

### ISSUE THREAD

**Issue by vagrant-drift** [AprilRobotics/apriltag#82]
I think intensitys  has nothing to do with the coordinates，why can create  intensity model using intensity(x,y) = C0*x + C1*y + CC2 ?  who can remove my doubts ,thank you!

**Comment by mkrogius** [comment]
The intensity model's goal is to correct for uneven lighting of the tag. For instance, if a flashlight is shining on the right side of the tag, the intensity will be an increasing function of x.

**Comment by vagrant-drift** [comment]
> The intensity model's goal is to correct for uneven lighting of the tag. For instance, if a flashlight is shining on the right side of the tag, the intensity will be an increasing function of x.

thank you！
