### ISSUE TITLE
One Question For Pose_estimate

### ISSUE THREAD

**Issue by Stephen-china-robot-star** [AprilRobotics/apriltag#83]
I detected marker and try to get pose of marker, but its show that undefined reference to 'estimate_pose_for_tag_homography'. And i did include the header file "apriltag_pose" in my program. Its strange that detect function is work normally, but estimate function do not work.so i just wanna ask why is that? thank u very much!

**Comment by vagrant-drift** [comment]
you can try homography_to_pose function。

**Comment by mkrogius** [comment]
Call estimate_tag_pose: https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation
